# Generated by Django 5.2.1 on 2026-03-04 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default_avatar.png', upload_to='avatars/')),
                ('description', models.CharField(default='', max_length=100)),
                ('post_number', models.IntegerField(default=0)),
                ('rate_number', models.FloatField(default=0.0)),
                ('rate_changed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-post_number', '-rate_number', '-user__date_joined'],
            },
        ),
    ]
